### ISSUE TITLE
Any testing on Raspberry Pi hardware?

### ISSUE THREAD

**Issue by everetteallen** [jeffpiazza/derbynet#10]
Sorry this is not really an issue but I wanted to see if you knew of anyone testing or using this setup on a raspberry pi?

**Comment by jeffpiazza** [comment]
I've tried running the server on a Model B+ running Raspbian, and connecting a couple of kiosks to it.  I think due to the access speed to the SD card (using a sqlite database), the web server's behavior is a little sluggish, but would likely be acceptable.  

Top reports total CPU load is around 40% while running the web server and a fake timer interface on the pi, while connecting from a coordinator dashboard and two kiosks.

Measuring the SD card's performance according to http://elinux.org/RPi_SD_cards#SD_card_performance, the card I'm using has a write speed in the 11 MB/s range, and reads just under 17 MB/s.
