### ISSUE TITLE
Feature Request - Play replays on different kiosks

### ISSUE THREAD

**Issue by chunter2** [jeffpiazza/derbynet#100]
With the new browser replay feature it'd be great if the replay could be played back on any kiosk, not just the replay kiosk.  This would allow one device to be set up in a good position to record the replay and a second device set up near a projector or large screen TV to display the "Now Racing" kiosk.

**Comment by ajspeck** [comment]
I have been exploring this idea in a separate branch at [replay branch in github/ajspeck/derbynet](/ajspeck/derbynet/tree/replay).  This is primarily to enable using a pi-zero camera to record the replay and then upload it the server where it is displayed along with the race results in a kiosk page.  The code for the pi-zero video replay recording is in the [derbynet-pi-replay](/ajspeck/derbynet-pi-replay) repo.  In order to enable the replay  I need to:

1. extend the photo.php concept to retrieve uploaded videos 
2. add an additional message parameter to the replay which defines the current replay-video-url
3. add the now-racing-replay.kiosk
4. I also added an ability to measure the difference between first and last finishers in order to extend the video replay for slow finishers.  This probably breaks the current replay implementation as it sends a float as the skipback parameter.  Potentially we should just add a second skipback-float parameter to maintain backward compatibility.

It would be good to discuss if this approach looks reasonable.

**Comment by jeffpiazza** [comment]
Sorry I haven’t responded earlier; it’s been a particularly busy week at work.

I have a few concerns with this, but it’s potentially not crazy.  I’d been working over the summer to allow a camera on one machine to stream video to a replay browser using webrtc — basically one-way video conferencing.  I should put the unfinished work on a branch in a day or two.  (The streaming seems to OK, but playing back the recording seems to show only the first frame, and I don’t know why.  I think I need to seek an expert.)  The beauty of a webrtc/browser-based deployment is that it neatly takes care of the cross-platform problem.

I agree that a pi+camera combination deployed apart from the replay screen is a really compelling use case.

The vision you’re describing might be workable, but my first thought is that there are several latencies involved, and they’re basically going to be experienced sequentially.  Also, relaying the video through the server adds (double) bandwidth loads on the server and network, plus read and write to storage, although a few seconds’ of video is perhaps small enough that it’s not a huge concern.  I’d like to see some benchmark measurements (heat end to playback start, over b- or g-WiFi) before committing too much time into the strategy.

The photo.php page is optimized to scale photos on demand; let’s not overload the same entry point for shoveling videos or other files around.

The current replay protocol is left over from the Mac Replay solution, which should retired.  The whole protocol needs a re-think.

I’m pretty happy with the current replay kiosk set-up, particularly in its use of iframe for separation of replay from the other kiosk content (like the now-racing page).  The now-racing page already has enough hair to do the end-of-heat animation; I’d prefer to see that not made worse.

Normally a PWD race is in the 3-4 second range, while the first finisher and last finisher are often within 0.1 seconds of each other, and many timers don’t trip until the last racer crosses.  Narrowing the playback to just the first-to-last finish range probably doesn’t serve the audience well.  (What *would* be interesting is adjusting the playback start and finish in the presence of DNFs, so the audience sees the racing part of the heat and not just the last 3 seconds of a stranded car on the track.)

There’s also the not insignificant question of codecs and video formats to consider.  Camera and playback browser would need to agree on an acceptable common content type.  For the pi with pi camera setup in particular, I’m not sure what the camera-side constraints are.

Finally, I want to be sure (if we can be) that the user isn’t confronted with having to choose among a bunch of competing and unrelated implementations of replay — it’d be important to have a unified user experience, with as much self-configuration as possible.

On the whole, I think a webrtc architecture, if it can be made to work, offers important advantages (peer-to-peer, cross-platform).  The main disadvantage is that it’s browser-based, which may make deployment of a headless camera device difficult.  (Maybe there’s a spec for the wire protocols, and a custom headless app could be developed.)

The other use case I haven’t investigated very far is whether cheap Chinese webcams, when they’re being controlled by hackers, could be incorporated into a remote replay functionality somehow.  This gets deeper into real-time streaming protocols than my knowledge goes, and I think most of these devices are hardwired you phone home to the manufacturer, but still you’d think there should be a way to make that work.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ajspeck** [comment]
I did a bit more testing on my setup using a Pi Zero W as the camera and a Pi 3B as the server connected over wifi (11n).  I see the replay appearing in the kiosk display at a little under 4 seconds from when the race finishes (which is maybe 2 seconds after the results animation appears).  This is well within what I consider acceptable so I am pretty happy with the solution.  In terms of media formats, the Pi Zero can natively hardware encode to h.264 so I am just using a mp4 container with h.264 encoded frames to upload to the server.

Regarding your point about making the implementations compatible, that is why I think the idea of uploading to the server is nice.  This way the replay display and acquisition can be completely isolated since the only requirement is to upload a playable video file to the server using the http post method -- in particular the existing web browser solution and my new pi based implementation both do this already.  

For the display I refactored a bit and made two new kiosk displays along with using a new page to retrieve stored videos.  One just shows the replay video full screen while the other uses iframes to combine the existing now-racing display with the new replay video by splitting the page in half.  This definitely seems to be cleaner as it reduces the dependencies between the two ways of displaying results and eliminates a lot of reused code.

**Comment by mwaldropdatastax** [comment]
This would be a great enhancement.  For us, we don't have enough projectors to run multiple large displays.  If we could have the "Now Racing" kiosk display also show the replay action between heats - that would be a major improvement.  There are ways we could do this today, but given the typical setup we would have to run a very long cable from the end of the track to the projector to make that all work.  Our preferred setup would be a pi server running software and timer, and a pi zero capturing replay.  All displays and kiosks would be run from laptops or random devices that are available.  And of course, the fewer cables that need to stretch across the floor, the better.

**Comment by chunter2** [comment]
One other idea would be to be able to use an Android or iOS device as the replay camera.  This would keep your idea of using a browser for the video.

**Comment by jeffpiazza** [comment]
Over the weekend I was finally able to get replay to work with video streamed from another browser.  The expected set-up is that one machine has a camera, and streams the video via the "Replay Camera" page.  A different machine (probably connected to a projector or similar) runs a replay browser, with "Remote Camera" selected as the video source.

This all works by leveraging WebRTC technology, which is still evolving and not yet fully implemented in all browsers.  So I expect there will be a good number of reports of situations where things don't work entirely as they should.

**Comment by chunter2** [comment]
Just had a couple derbys last weekend and remembered this.  I couldn't seem to get the Remote Camera to display.  It just came up blank.  Would you be able to share your hardware setup you had for testing this out so I can compare?  I wouldn't mind taking some time to help debug this now that they're done.  

By the way, two more successful derbys.  :)  

Thanks
