### ISSUE TITLE
Bug: Slow replay performance and kiosk performance

### ISSUE THREAD

**Issue by joncamp** [jeffpiazza/derbynet#107]
We ran our derby last night. Overall system worked out great, especially for our first time using it. However, I found the performance of the replay system to be pretty bad overall.

Setup:
Private WiFi router/access point (Netgear 802.11n). Router not connected to internet
DerbyNet Server running on Surface Pro 4 on Windows 10, java timer applet. Connected via USB-Ethernet adapter directly to router/access point
DerbyNet Replay Kiosk running on Surface Pro 4 on Windows 10 replay and connected to projector. Connected to server via wifi

Overall the perf to the kiosk was pretty laggy - it seemed to take a few seconds for changes in the derbynet UI to update to the kiosk. The replay was pretty choppy overall, but did work.

Next year I will definitely hardwire both, but it seems like this should not be taxing the system that much. Thoughts?

**Comment by heatvent** [comment]
How was the CPU performing on the kiosk? I was testing this with a win 10 i5 laptop and a chrome browser.  The laptop was hosting derbynet, the timer and the kiosk.  With the kiosk window open and not doing anything the CPU went up to around 97% largely driven by Chrome.  The whole system got sluggish although with enough patience I was able to start a race and it worked.  However way too taxing for prime time.  I was going to try with another browser or just repeat to see if it was a bit of a fluke.

**Comment by joncamp** [comment]
I was running chrome on all systems. Pack had 64 racers in system total, with 44 checked in for racing. All racers had car photos which were used on various screens.

**Comment by heatvent** [comment]
I just did another quick test.  The laptop is actually a 7th gen Core i7 2.7ghz with 8gb of ram and Radeon graphics. Not high end but decent specs. I used Edge to run DerbyNet and Chrome to be the replay kiosk ... all on the same PC with the timer running in simulation mode.  Using Edge seemed to help a bit with lag of the GUI. 

Idling, the PC floated around 80% CPU. If you touched anything it shot up to 100% and throttled.  Strangely, task manager shows an Intel HD Graphics GPU and a Radeon GPU.  The Intel HD GPU was at 1% and the Radeon GPU was flatlined at 0%.  So the processing looks like it is all CPU but his is just a webcam so not sure where all the processing is coming from.  

Maybe there is a tweak somewhere that I need to do as this seems too taxing for recording and replay of a webcam.

**Comment by jeffpiazza** [comment]
@joncamp I think you're describing two different issues, although I guess they could be related.

Everything in the kiosk works by polling the server, and different polling streams (there are several) operate at different frequencies.  For example, the poll to determine whether the kiosk should switch to an entirely different display (now-racing to awards-presentation, say) is pretty leisurely, to minimize network and server load; it can take 2 or 3 seconds before a kiosk page change occurs.  In contrast, the polling the replay page does waiting to know that a heat just finished occurs several times per second.  It'd help if you could identify particular interactions that lead you to say it's "laggy."  (Not trying to cast doubt on your perceptions, just want to get to specifics of what we're talking about.)

(As an aside, I'll say that while most places we've run derbies have reasonable wifi performance, when we run an event at our local mall, my stand-alone wifi router gives terrible performance -- it's infeasible to capture still photos and transmit them wirelessly.  So maybe the wifi's a factor, but, like I said, in my experience, in most venues it's not necessary to use ethernet end to end.)

Performance of the video playback itself, on the other hand, has nothing to do with polling latency, and, once triggered, doesn't involve the server in any way.  Choppiness is presumably attributable to the demands of decoding the video.  (A lot of webcams encode the video, e.g. to mp4, in the camera, but the host is on its own to do the decoding for playback.)  I don't know anything about Surface Pro and what sort of GPU it supports, and I don't know what kind of camera you were using, and what video format the browser would choose; performance here can vary dramatically.

@heatvent: While the replay page is active (showing a kiosk page), it's constantly recording the video stream coming from the camera.  Under normal settings, it's making 4 recordings simultaneously, each spaced a second apart, so that the last four-second clip can be played from the beginning.  (There doesn't appear to be a simple way to seek/skip back to an arbitrary point in a recording.)  This strategy of capturing multiple recordings is something of an extravagance, and can pretty well occupy one core of the CPU (hence the warnings about the performance demands of using replay), but still leaves a lot of computing power in a modern multi-core laptop.  I haven't observed server performance to suffer even when running on the same laptop as a replay kiosk, but YMMV.

**Comment by joncamp** [comment]
I am less concerned about the changeover time from, say, the flag image to the welcome image or whatnot. More calling it out as correlating to the general slowness.

My two machines are Surface Pro 4 core i5-6300U @ 2.4ghz 8gb ram. They both have an Intel HD 520 GPU.

Webcam is a logitech C930e. The videos seem to have been saved as an mkv, happy to pull whatever specs you would like that would help.

**Comment by joncamp** [comment]
One odd thing that I noticed - on a surface pro 4 there are 3 onboard cameras - Front, rear, front IR. The front IR has an IR emitting LED that is visible when it is on. On my machine I added a 4th camera (the logitech) to capture the race. However, I noticed that the IR emitter is on even though I selected the logitech. In addition, the white inidcator light for the front facing camera is also on. I wonder if you are opening all the cameras simultaneously...or perhaps opening 4 streams on each of what ends up being the 4 cameras?

For verification, I used the built in camera app and ensured that when switching to the various cameras, the LED indicators properly turn on or off when the associated camera is in use or not.

**Comment by heatvent** [comment]
Jeff, that makes sense from how you have it setup.  I did see considerably worse performance with the HD Lifecam than the built-in webcam, but both ran up the CPU usage.  FYI, I wasn't complaining, more or less just stating that at that level of performance I would be concerned to use in a live environment. Other setups obviously may work better but I think the lesson learned is test this first.  I did see the warnings on performance but expected this to have less impact on a laptop with these specs.  Anyway, great work on DerbyNet, it is an awesome product.

**Comment by chunter2** [comment]
Just tried doing a few test to check CPU usage.  My setup is the server running on a Raspberry Pi 1.  It's headless.  I've got an old Toshiba laptop that's got an Intel Pentium Dual-Core T4500, so not that fast.  When I use the integrated webcam my CPU usage goes to about 60%.  It shows up as "Toshiba Webcam" in device manager.  When I use an external webcam the CPU usage goes up to 90%.  The external webcam shows up as "HD Pro Webcam C920".  When I leave the external webcam plugged in but use the internal one the CPU usage goes to a little less than 90% but not down to 60%.  The percentage numbers are all guesses as I watch the task manager box in the taskbar.  So it seems something extra is happening when multiple cameras are plugged in.  

Would it also be an idea to add a resolution selection when choosing the camera to use for the replay kiosk?  Maybe lowering the resolution would help with CPU usage.  I think the projector I'd be using is only 1024x768.  I'm not sure what resolution either of these webcams do.

**Comment by joncamp** [comment]
So part of the issue seems to be that the camera streams may not be properly closed when switching between the various cameras on a system. If you have one camera - you are golden. If you have two or more cameras and then select a different one, then any previous camera still seems to be active (the indicator lights remain lit, which are generally hardwired to prevent being disabled).

Repro:
Connect multiple webcams to your replay system. Ideally external webcams with an indicator light of some sort.
Open the replay.php page, select the various cameras until you have selected all of them
Click proceed

Result:
Notice that the indicator lights for all the webcams stay one throughout the selection process (once initially selected), and stay on after the final camera is selected and the proceed button is clicked

**Comment by joncamp** [comment]
This seems to fix the multiple open cameras issue:
```
function on_device_selection(selectq) {
  stream = document.getElementById("preview").srcObject;
  
  if (stream != null) {
    stream.getTracks().forEach(function(track) {
      track.stop();
    });
  }
  
  let device_id = selectq.find(':selected').val();
  navigator.mediaDevices.getUserMedia({ video: { deviceId: device_id } })
  .then(stream => {
      g_recorder = new VideoCaptureFlight(stream, 4, 1000);
      document.getElementById("preview").srcObject = stream;
    });
}
```

**Comment by chunter2** [comment]
Just tried out this latest fix and it works.  I can see the lower CPU usage when I select the onboard webcam and still have the USB webcam plugged in.  

I did try adding the following to the VideoCapture function in video-capture.js right before the start() to see if I could lower CPU usage.  
 `  recorder.setVideoSize(640,480);`
It seems to lower CPU usage but the test replay button stops working.  My googling skills are failing me but it seems like it could be an easy hack for my low powered laptop.

**Comment by TheGlobalMind** [comment]
Our single replay kiosk seemed to work pretty well. We initially did see rather slow performance over wifi especially if the kiosk was set to something like welcome in addition to being a replay. Switching screens was really slow. Generally, the wifi side for all other kiosks worked great, but for the replay, we decided the laptop was close enough to the router I am using, that we just hard-wired it in, and that definitely helped.

**Comment by heatvent** [comment]
Not sure when this fix was pushed out.  I updated DerbyNet on Sat morning ... our race was yesterday and we went without the video replay as I didn't want the possibility of lag / performance issues.  I actually tried this on the same laptop I was testing with on Friday and with video replay going, the CPU was around 20% which is very usable.  I am assuming the fix was pushed to the Sat build I updated to.

**Comment by joncamp** [comment]
@jeffpiazza Question about the design of the overall system. Is there a reason why you didn't go with a  circular buffer? Seems like it would be sufficient to keep a 15 or 20 second circular buffer. Assuming a worst case 10 second timeout (as is the case for many timers), that still leaves time for plenty of buffer on either side of the finish. Further, if you keep track of the events (ie: Race start, race end) you have the associated data necessary to find the other critical points (ie: end point of each finisher, by using their times). The main benefit would be to further reduce overhead (especially on lower performance devices). https://paul.kinlan.me/simple-boomerang-video/ has some info on a somewhat similar concept that manipulates the frame array.

**Comment by jeffpiazza** [comment]
That all looks promising.  The media handling APIs are new to me, and seemed surprisingly limited.  ("It’s also been said to be impossible to do on the web in real-time," says your link.)  It looks like maybe canvas elements are the way to get access to the frames within the stream, which is the main missing piece to the puzzle.

**Comment by chunter2** [comment]
Just updating my previous post about resolution.  I was able to set the resolution by changing the getUserMedia line in replay.php to this.
`navigator.mediaDevices.getUserMedia({ video: { deviceId: device_id, width: {exact: 1024}, height: {exact: 768} } })`
I can't say this helped CPU usage much.  Changing the resolution to 320x240 did help but isn't really worth displaying since it would be so grainy zoomed to 1024x764.  I'm starting to think 4 streams is just too much for this laptop.

**Comment by jeffpiazza** [comment]
I'm not really sure where we stand with this issue anymore.  Performance is always a concern, but with the PR from @joncamp, the rewrite in e35ea6ed0f717f3163a7b82674e0ae614cab67fd, and the framerate changes in 5040ac814930e295177f2b0572219888a0213ac4, I think we're at a more-or-less acceptable performance level.

Perhaps more to the point, I don't have any ideas on how to achieve better performance, though I'm certainly open to suggestions.

I'm going to close this issue for now, but please feel free to open new issues as needed.
