### ISSUE TITLE
Pack Standings is same as Grand Final Aggregate

### ISSUE THREAD

**Issue by joncamp** [jeffpiazza/derbynet#123]
This is related to #109. We ran our pack at the den level as groups, then ran an aggregate round to determine the fastest 3 of the whole pack. Previously the pack view was blank. With #109, the pack view now matches the Grand Finals aggregate view. That seems rather surprising. I would expect it to be the pre-aggregate results. The problem is that our grand final included 21 racers out of the total ~45 that ran. 

One reason for the desire for overall pack standings (especially if pulled from the pre-aggregate) is to do things like find the "most fuel efficient" car (ie: slowest) out of the whole pack.

Result: Pack and Aggregate show the same data. Pack view only shows 21 of the 45 racers
Expect: Pack shows data from all 45 cars, either pre-aggregate rounds (ideal) or including results of the aggregate.

**Comment by jeffpiazza** [comment]
Standings definitely needs to be more transparent about what's going on.  Confusion is just about inevitable with the current situation.

Here’s a thought experiment: set aside Grand Finals per se, and imagine a race with exactly one group.  After the first round of racing, the top half of the group goes on to a second round, while the lower (slower) half of the racers do not.  Now suppose one of the cars in the second round loses a wheel or otherwise suffers some catastrophe, and fails to finish several heats in the second round. The average time for that racer, taken across either all heats run, or just its second-round heats, will likely be much slower than the average time for, say, the fastest of the eliminated racers.  So, when constructing a standings page for the whole race, should the eliminated racers have better standings than the car that advanced and met mishap?

I’ve been viewing the creation of follow-on rounds, including Grand Final rounds, as an elimination process.  That is, racers who didn't advance to the final round are no longer under consideration for standing in the group -- they were eliminated, and their times from the first round aren't comparable to results from racers who were in the second round.

In the presence of a Grand Finals round (i.e., round(s) for a single aggregate class), the code considers the GF round to be the determinant of overall (Pack) standings.  If there are two or more aggregate classes, then no overall standings are offered.  The "single aggregate" rule is really just a guess, but the only possibly "better" alternative I can think of is to turn off Pack standings if there are any aggregate classes at all.

I agree absolutely that there should be a view of standings from the set of rounds from which aggregate class racers were drawn ("pre-aggregate" standings, to use your term).  There would need to be some accompanying education effort, though, because the reasoning is pretty hard to convey in a simple UI.

**Comment by joncamp** [comment]
Thinking about den round times vs. final round times - in most other sports it wouldn't be an issue. Consider the Olympics: You have lots of qualifiers to get into the Olympics for the 100 yard dash. Now, you might have a super awesome day and get a new world record during your qualifier for some reason. You go to the Olympic games and you psych yourself out and pull a hamstring during the final race. Your time is way slower than many people who would have qualified...but thats just how it goes.

Applying the same logic to PWD, perhaps "pack" is a misnomer in this case, but the assumption is that "pack" is an aggregation of all the den qualifying rounds. The Grand Final is a second set of rounds connected to the qualifying rounds only by the nature of the participants. If your car breaks in half during the grand finals that doesn't mean the 4th place car from your den gets inserted into the grand finals once racing has started.
