### ISSUE TITLE
Printables off by one error

### ISSUE THREAD

**Issue by jaeaton** [jeffpiazza/derbynet#165]
On the printables page the  racer numbers vs generated rank (100 -> Lions, 200 -> Tigers, Etc) displays 100-> Tigers, 200->Wolves, etc. I am unsure if this affects anything else.

DerbyNet-v7.0-1393-20211203.win

**Comment by jaeaton** [comment]
Looks like images (in www/images/) should be renumbered IE 000-series.jpg should be 100-series.jpg

**Comment by jeffpiazza** [comment]
I think actually the issue here is that the default numbering for cars starts at 101, while the expectation for the car-tag printables is that they start at 1.  So the idea is that Lions are 1-99, Tigers are 100-199, and so on.

(The idea was that the hundreds digit would match the grade, so zero for kindergarten, 1 for first-graders, etc.  But since leading 0s aren't normally displayed, this "pun" may be too subtle to have value.)
