### ISSUE TITLE
Feature Request: Calculate Standings over Multiple Rounds

### ISSUE THREAD

**Issue by Zaimor** [jeffpiazza/derbynet#182]
Feel free to enlighten me if I'm mistaken in my assumptions, but we just wrapped up a race day and in reviewing the data, I discovered that DNet awarded overall 1/2/3 and subgroup (den) 1/2/3 based on Round 2 results only. I was under the impression that it would have tallied results based on Round 1 + Round 2 (3+3=6 heats per car). If this is by design, would love to have the option to do it.

**Comment by jeffpiazza** [comment]
You're correct in observing that standings for a group are based only on the last racing round for that group.  This supports a use case of elimination rounds (only the top N from the first round advance to the second round).

If your goal in having two rounds is just to provide for more racing, there's a "runs per lane" value you can set when scheduling a racing round.  So instead of (say) two rounds in which each racer races once per lane, you'd have one round in which each racer races twice per lane to get the same number of runs per racer, but all within a single round.

If you need an intermission, you can just pause in the middle of the single racing round.  There's admittedly a chance that a given racer might see more of their runs concentrated on one side of the midpoint or the other.

I'm going to close this FR for now as not something I have plans to support, but if you have a use case I'm not thinking of for why you prefer a two-round structure, I'd love to hear it.
