### ISSUE TITLE
Racing Groups

### ISSUE THREAD

**Issue by jaeaton** [jeffpiazza/derbynet#185]
When editing the Racing groups in the Racing Groups Editor the following message pops up:

Ajax error: Internal Server Error

Console log:
[ajax error.log](https://github.com/jeffpiazza/derbynet/files/7990377/ajax.error.log)

**Comment by jeffpiazza** [comment]
Any chance you can find the server (error) logs and/or php_error.log?

Could you send me an export of your database (from the About page)?  (Don't need last names, or you can email the export just to me.)

**Comment by jaeaton** [comment]
Apache Log:
[error.log](https://github.com/jeffpiazza/derbynet/files/7990470/error.log)
PHP Log:
I don't know where this is
about page database:
[derbynet-20220202-223724.txt](https://github.com/jeffpiazza/derbynet/files/7990506/derbynet-20220202-223724.txt)

**Comment by jeffpiazza** [comment]
Only happens on Windows: the version of php-sqlite I'm using for the Windows version is getting pretty old.  Hope I remember how to update!

**Comment by tfrazee** [comment]
I have the same error.

[error.log](https://github.com/jeffpiazza/derbynet/files/7991439/error.log)
[derbynet-20220202-203838.txt](https://github.com/jeffpiazza/derbynet/files/7991447/derbynet-20220202-203838.txt)

**Comment by jeffpiazza** [comment]
I just built a new Windows distribution with an updated Uniform Server.  Updates to UniServer are never completely straightforward in my experience, so I wonder if one or two of you could try putting some air miles on before switching over for everyone.  Download the latest version here:

https://www.jeffpiazza.org/derbynet/builds/dist/DerbyNet-dev-1473-modified-20220202.win.zip

If after starting Apache you see raw PHP source instead of the normal landing page, you may very well need to update the Visual C++ Redistributable for Visual Studio 2019 from 
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
(check the Apache error log to confirm).

jaeaton, you'll probably need to switch to "racing by den" and then back to "custom racing group" in order to repair the database corruption you have presently.  tfrazee, very possibly the same applies to you.  (The symptom is that no partitions show up in the "custom racing groups".)

**Comment by tfrazee** [comment]
Jeff,

I am not running on windows, but on ubuntu. SSL certs by Let's Encrypt if that matters at all.

**Comment by jeffpiazza** [comment]
Tim, what does

sqlite3 -version

say for you?  3.27 seems to work, 3.15 doesn't, and I'm not sure about in-between.

What version of Ubuntu are you running?  Can you try  apt upgrade sqlite3 ?

I may just have to dial back the problematic SQL statement if version problems are going to be widespread.

**Comment by jaeaton** [comment]
I had no errors with 1473

**Comment by jeffpiazza** [comment]
I rewrote the SQL statement so it works with older sqlite implementations.  I also updated the UniServer version for the Windows builds to use a more current sqlite and PHP.  Between the two, I think it's safe to call this closed.
