### ISSUE TITLE
Getting error when login in

### ISSUE THREAD

**Issue by JoseanDonis** [jeffpiazza/derbynet#188]
I'm know getting the following error Login fails: upgrade your derby-timer.jar (shoulld be using role.login to login).
I did the setup it was working fine and now I cant login. Try to do a new setup and I get the same issue also not showing some buttons and if I go to printables I dont see the roster there as I use to. also if I try open a kiosk it will not show the kiosk on the list.

**Comment by jeffpiazza** [comment]
If you're seeing the "login fails" message from derby-timer.jar, be sure you're using a derby-timer.jar that came with v7 -- download a new copy at https://jeffpiazza.org/derbynet/builds/derby-timer.jar if you need to.

For the rest, it sounds like you're describing several different things at once, and I think I need you to describe your process in some more detail.

Are you running the server on a laptop or somewhere else?  What does the login page actually show when you try to log in?

**Comment by acespacepilot** [comment]
Having the same issue with the new release when trying to login as either RaceCoordinator or RaceCrew.  Using default passwords (never changed them). After typing in password, receive a popup on the browser that says "Login fails: Please upgrade your derby-timer.jar (should be using role.login to login)"

Restarted Apache but no joy. Can't seem to get past this.

**Comment by jeffpiazza** [comment]
I'm still having some trouble understanding the context here.

If you're seeing "upgrade your derby-timer.jar" in derby-timer.jar, then do download and use the latest derby-timer.jar instead of the one you're using.

If you're seeing this in your browser while trying to log in, then my only guess is that you've recently upgraded to v7.0 and your browser is using a cached older version of the login.js script.  In that case, flush the browser cache by doing a "hard refresh," https://www.documate.org/resources/what-is-a-hard-refresh-how-to-do-a-hard-refresh-in-any-browser.

Please let me know where you're experiencing this.
