### ISSUE TITLE
Web-based version of docs

### ISSUE THREAD

**Issue by mikesir87** [jeffpiazza/derbynet#203]
Curious... would you be interested in having a web-based version of the docs, rather than using PDFs? It would make it easier for others to help maintain and improve them, as well as make the docs more searchable. I've had a lot of experience with using static-site generators for docs (like Hugo and mkdocs) and could help out with this. They'd all be written in Markdown, but converted to the normal web format.

Thoughts?

**Comment by jeffpiazza** [comment]
Intriguing!  I think I have more questions than thoughts.

Do you have a more focused comment or request about the existing documentation?  Is there a hole that needs filling?  Is the concern that the existing PDFs are just boring?  That they're too linear?

Would you suggest a different structure or organizing scheme?

Would web-based docs help with #176?

**Comment by texnofobix** [comment]
I recommend moving it to a markdown format

**Comment by lordscarlet** [comment]
I am just diving into this, but I am completely lost. I can get a docker image up and running, I can use the UI int he hosted version, but I want to look at making modifications and submitting PR's. I am trying to find documentation on running the site locally. I can _probably_ hack together everything after a few hours of digging. I see that it uses PHP, and possibly sqlite. But it seems like there should be some documentation to quickly get up and running locally, even better if it uses docker images so that I don't have to install anything for hosting and databases. 

I have yet to find anything that can read the documents in the `docs/` folder. Everything is just a little obtuse. Or I am. Or both.

**Comment by jeffpiazza** [comment]
I think you're asking, approximately: how to get a working installation from a cloned repository.  Fair point that that's not at all well documented!

As a stopgap response: Here's the docker command I use locally (on Mac):

docker run -d -p 80:80 -p 443:443 \
     -v ~/Public/DerbyNet:/var/lib/derbynet \
     -v /etc/localtime:/etc/localtime:ro \
     --mount type=bind,src='_**(path-to-your-local-sources)**_',target=/var/www/html,readonly \
     jeffpiazza/derbynet_server

From the cloned repository, you _might_ need to do:

ant generated

before it can work, to build a few generated files.

**Comment by lordscarlet** [comment]
What is in `~/Public/DerbyNet`?

**Comment by jeffpiazza** [comment]
As the discussion seems to have migrated to #285, I'm going to close this issue.
