### ISSUE TITLE
Lion Rank image not used

### ISSUE THREAD

**Issue by HayS33d** [jeffpiazza/derbynet#214]
in car-tag/document.inc 
line 74: divides the car number by 100, however the minimum car number is 100 because dens do not appear to be a zero based array
The lion rank image starts with 000-
the first entered den is 1 not 0

**Comment by jeffpiazza** [comment]
Do you have a repro case that demonstrates your concern?  I having a little trouble understanding your issue.

The "Lion Den" image is in 000-series.jpg, and gets assigned for car numbers 0-99.  (Or, at least, that's the idea, and as far as I can tell, that's what it actually does do.)  I expect there's a sizable fraction of the population (including sometimes me) who finds this awkward or unnatural, as car numbers should "obviously" start at 100 or perhaps 101.

If you're saying something to the effect that the first car entered is being assigned a car number in the wrong century, a repro example would be helpful.

**Comment by HayS33d** [comment]
I believe after I purged the racers from the database, when I re-added the dens (that seems to get purged too) the first den I enter becomes ID 1 rather than ID 0. making the first century 1, thus making tigers the first Rank image used.

**Comment by jeffpiazza** [comment]
The internal ID numbers for classes, ranks, racers, etc., aren't used for image selection, and the user doesn't have any means of controlling their selection.  The number that determines which image is used on a car tag is the user-visible "car number" field.

Car numbers can be included in the roster import, and edited in the check-in page.  There are also "bulk renumbering" operations available on the check-in page to help manage getting car numbers into the right centuries.

If you still think there's an issue to fix here, I'd appreciate a repro case, otherwise I wonder if you'd consider closing this issue.
