### ISSUE TITLE
Support uploading image sets

### ISSUE THREAD

**Issue by burnclouds** [jeffpiazza/derbynet#223]
Would be nice to allow image set uploads.
Also created a pull request for an Awana Image Set (#240)

**Comment by jeffpiazza** [comment]
With v9.0, users can provide their own imagery and/or slides to customize their installation; details are described in the appendix to the "[Running a Race with DerbyNet](https://derbynet.org/builds/docs/Running%20a%20Race%20with%20DerbyNet.pdf)" document.

For hosted instances on hosting.derbynet.org, instance owners can now upload custom imagery and slides for their event.

I've also set up https://derbynet.org/image-sets/ as a repository for image sets for various youth organizations.  In the longer term, I'd prefer to move toward this kind of self-serve model.

**Comment by speeddesigns** [comment]
> For hosted instances on hosting.derbynet.org, instance owners can now upload custom imagery and slides for their event.

Can you tell us how to do this on a hosted instance? I can't seem to find it and trying to duplicate the file structure on the hosted instance doesn't seem to work (not surprisingly).

**Comment by jeffpiazza** [comment]
@speeddesigns, the  "DerbyNet in the Cloud" email that comes when you register a hosted instance includes a link to the image uploading page.  The link includes a secure token (rather than a password), to prevent vandalism of the hosted instance by unauthorized users.

If you're asking about a playground instance, I'm realizing as i'm writing this that I don't have a ready answer for that at the moment.

If you're instead asking about how to handle custom imagery for a server you're running on your own machine, the relevant file paths are described in the appendix to the "[Running a Race with DerbyNet](https://derbynet.org/builds/docs/Running%20a%20Race%20with%20DerbyNet.pdf)" document.

**Comment by speeddesigns** [comment]
I was talking about the playground instance, yes. Perhaps I should request an ahead of schedule "race day" instance to finish testing before the actual race day?
