### ISSUE TITLE
Bar codes not working in 8.0

### ISSUE THREAD

**Issue by burnclouds** [jeffpiazza/derbynet#224]
Set up an excel file imported racers, printed car tags, but Barscodes dont seem to work the way I'd expect.

#PWDid031
#PWDid011
Are whats is scanned in by my  LS2208-SR20007R-UR but the "find Racer" feature in the check-in page doesn't find a result.
Additionally the Racer Check in and Driver License printables don't seem to scan at all.

**Comment by jeffpiazza** [comment]
The barcodes are supposed to read as e.g. PWDid031, without the leading "#" character.  They use the "code 128" symbology.  The search bar in the check-in page expects the "PWD" prefix at the very start of the string in order to recognize as a barcode scan; that could be changed if there's no other way to deal with the "#".

Is it possible that your scanner is configured to send a "#" character as a prefix, or that it's configured for UPC only or similar?

In my own experience, I've noticed that barcodes printed on an inkjet printer in normal "draft" quality are less reliably scannable.  I don't have a sure-fire recipe for what will or won't scan, but I think experimenting with different printing regimes may help you.  I also have an as-yet-unproven hypothesis that smaller barcodes may scan MORE reliably than larger ones.
