### ISSUE TITLE
Kiosk setup not working on Pi 2

### ISSUE THREAD

**Issue by Jchuchla** [jeffpiazza/derbynet#235]
I know that Pi 2 is now an old model, but I'm finding myself trying to use them due to the current scarcity of more recent Pis.  I set up a Pi 2 B+ as a kiosk as per the derbynet instruction manual for debian.  I did not install derbynet on this pi.  Only the derbynet extras package.  It does take a very long time to boot, and when it finally does come up, it comes up as a blank white screen.  If I alt-tab i can confirm that it is using the chromium browser.  I believe that's the only browser on the current "basic desktop" official pi image.  If I exit the full screen mode and am fast enough before the script tries to restart the browser, I can open chromium again and navigate directly to the derbynet server IP and the page does come up.  

I can't figure out how to see what page it's trying to load when it's in full screen mode or figure out why the page doesn't come up.

If I pull the SD card from the Pi2 and insert it into a Pi 3, it boots and comes up into the kiosk page perfectly.  So this seems to have something to do with the Pi 2 and how the script is set up to load the page.  Maybe a timing thing since the Pi 2 is so much slower?

**Comment by jeffpiazza** [comment]
If you can ssh to the pi, you can try killing the autostart script.  Otherwise, you could try exiting full-screen mode and opening a terminal.  It may well be easier just to re-image the card and start over.

Assuming you have control of the pi, open a terminal window and try running /usr/share/derbynet/scripts/kiosk.sh.  Alternatively, you could look in that script to work out the command line that will be used to invoke chromium, and try removing options as needed.

The page it's trying to load is kiosk.php from the DerbyNet server; the latter's address or hostname (and path prefix, if necessary) is expected to be in the DERBYNET_SERVER environment variable, set by /etc/derbynet.conf or /boot/derbynet.conf.  Try opening the browser's javascript console to see if there are any smoking-gun errors shown there.

I can understand the Pi2 being slower than a Pi3 (the Pi3's a quad-core part), but I'd expect it eventually to finish rendering.

**Comment by Jchuchla** [comment]
When I kill the fullscreen browser and open one manually from the desktop, the script will eventually try to open the page again.  And when the browser is already open it does it in the form of new tabs in the existing browser without going full screen.  since it's not the same process it thought it started, every few minutes, it opens a new tab with the kiosk view.  But it doesn't just open one tab, every time it triggers, two tabs actually open.  One is blank and has a title with incognitio in the name.  I'm not in front of it now but it also had some other random characters in the page title.  The other tab is the derbynet kiosk that does load content properly.  So I suspect this is happening on initial load too when the script does it.  But what's showing full screen is that blank incognito tab rather than the derbynet tab.  I think the script needs to be modified in my case somehow to prevent that other tab from opening.
The odd thing is that this isn't happening with the same SD card when i put it in a pi 3.

**Comment by Jchuchla** [comment]
Update.  I thought these were Pi 2s I was testing with, but something wasn't jiving with arm versions as I was troubleshooting the timer issues.  These are actually older than that.  These are the older Pi Model B+ Rev 1.2 with the BCM2835 cpu.   I had the box labeled wrong.

Side note:  The irony of this is that one of these two Pis was just pulled from duty running my signage for my christmas light show.  The only reason I upgraded the pi for that application was because it was taking too long to boot, and too long to recompile updates.  It was otherwise working just fine as a kiosk in the front yard!  Though that image didn't have the linux desktop installed.  That's a fair amount of overhead.
