### ISSUE TITLE
MySQL Missing in Windows

### ISSUE THREAD

**Issue by JELollis** [jeffpiazza/derbynet#243]
I am attempting to set up on my home test environment under IIS8 and I keep running into issues with the database saying "driver not found" for SQLite. I am not given any option for MySQL, which would be the preferred method for setup for my needs. Is there a specific way to add this option that I seem to be missing?

**Comment by jeffpiazza** [comment]
If you're having a problem with Sqlite support (i.e., that's not a typo): Sqlite support for PHP is an included-by-default extension for PHP.  Maybe check with phpinfo to see what's going on there: https://www.php.net/manual/en/function.phpinfo.php#refsect1-function.phpinfo-examples.  You need sqlite and pro-sqllite, https://www.php.net/manual/en/ref.pdo-sqlite.php.

MySQL support in DerbyNet has been retired since da826302527669b56b3252773542678de7f8506e (in 2019).  You could try editing the config-database.inc file to set a connection string like: "mysql:host=localhost;dbname=my-database".  It should mostly work, but there may be occasional SQL differences.  You'd need the pro-mysql extension in PHP, of course.

**Comment by JELollis** [comment]
I was unable to get it to work either with SQLite or MySQL, but I was able to utilize your hosting option and it works just fine that way. I assume it may be an issue with IIS more so than anything else.
