### ISSUE TITLE
Barcode Generation

### ISSUE THREAD

**Issue by MeepBeep** [jeffpiazza/derbynet#271]
Playing around with 'car tag' I have run into an issue, that being the Code128 barcode being generated appears to be a little wonky and some scanners are not reading it properly.  In the attached image, the top is the barcode generated by DerbyNet, the middle is the DerbyNet barcode shrunk width-wise to better align with an online generated barcode at the bottom for comparison of line weight and spacing.  It appears that the DerbyNet barcode line weight and the spacing are a little wonky and likely causing errors?

I currently have two scanners on hand, one will scan all three of these properly, and the other (your run of the mill Asian import model) will truncate all the DerbyNet-generated barcodes to only 7 characters aka it scans the DerbyNet barcode below as pwdid01 dropping the 6 (8th digit) it drops this 8th digit on every barcode generated by DerbyNet.  The scanner is properly configured to read Code128 and will read the online generated Code128 in the picture just fine, just not the one created by DerbyNet.

Neither of my scanners will scan the 'check-in card' at the default printing size, I'm printing on a laser printer and it's a crisp and clean barcode but the scanners refuse to scan it.  I shrunk the online generated Code128 to even smaller than the barcode on the 'check-in card' and both scanners scan it, so it's not an overall size or resolution issue from printing.

![barcode_compare](https://github.com/jeffpiazza/derbynet/assets/30540955/3232e5a0-373c-43d8-90c8-f7cad99248e1)

**Comment by jeffpiazza** [comment]
Thank you for your extensive investigation!

It turns out that horizontal and vertical bar codes are rendered by different code paths, and now that you point it out, I see there are some off-by-one issues with horizontal bar codes, as would be used in check-in cards.  I couldn't scan a check-in card, either, trying just now.

On the car tags, there's a large vertical bar code and a smaller horizontal one.  The vertical one scans OK, but the horizontal one didn't, just now.  (I didn't try pulling out other scanners.)

(I use car tags for the various derbies I run locally, but must have overlooked hand-testing check-in cards.  And I forgot that horizontal and vertical go through different code paths, so it never occurred to me that verifying one didn't entirely validate the other)

Just to add to the confusion: I tried generating the "PWDid016" code myself this morning, using Code128 at https://www.barcodefactory.com/code128-barcode-generator, and get a slightly different result than in your image, at least to my eye.  That might be some sort of resolution issue with capturing images on screen.

I'm about to post up the fixes to the off-by-one bugs, and tentatively mark that a fix to this bug.  If you still have trouble or want to investigate further, please feel free to re-open.

<img width="568" alt="image" src="https://github.com/jeffpiazza/derbynet/assets/13140826/f887dcb1-7160-4b51-9b46-bca8b8711f4f">
