### ISSUE TITLE
Feature Request:Scaling on racing screen

### ISSUE THREAD

**Issue by heatvent** [jeffpiazza/derbynet#28]
If I just use scout names all 6 lanes show up nicely in the now racing screen.  However, if you add car names there is a full empty line between the scout name and the car name making each row/lane take 3 lines of text which causes lane 5/6 to go off screen unless you scroll down.  Would it be possible that the car name is directly under the scout name to save 1 line and then to have the text scale based on the size of the screen.

**Comment by jeffpiazza** [comment]
I experimented a little this summer with a more sophisticated font-size selection strategy, but didn’t get to anything I liked.  The current layout rules seem to “mostly” work, but you’re not the first to report an issue.

The 3 lines of text should just be two; that's a bug that's now fixed in the 679 build, posted just now.

Assuming you're still having problems after that, if you’re willing to poke around a little, you could work around the problem by modifying /var/www/html/derbynet/css/now-racing.css, which controls the font sizes for this display.

(1) There’s a default maximum font-size of 85px (line 66).  

(2) You’ll notice clauses like this:

@media screen and (max-width: 1400px) { … }

that select smaller font sizes for smaller screen widths.  (Note that these max-width rules have to follow the default, and have to be in decreasing max-width order.)

If you do this and get something you like better, please advise what font size you ended up with, and what your screen dimensions are.  (As a convenience, screen dimensions are shown on the Identify kiosk page.)

**Comment by heatvent** [comment]
Let me try with the new build.  The double line was probably causing most
of the issue.  I am using my laptop which as a 1920x1080 resolution.  The
kiosk page reports back reports back a resolution of 1536 x 734 in normal
mode and 1536 x 864 in full screen mode using Chrome on Windows.  Is this
right?

FYI, I did poke around and found the @media font sizes ... thanks for
pointing that out though.

I will report back how it works with the new build.

**Comment by heatvent** [comment]
OK, it seems to be worse.  The extra line is gone but the font seems to be going to the maximum and you can see maybe 3 lanes of data.

**Comment by heatvent** [comment]
Jeff, I tried again this morning and it seems better...not sure why the font was so large but maybe closing and reopening the browser helped.  I can now change the default size of 85px to something else and it changes on the screen.  I found 32px when in normal mode and 36px in full screen mode to fit the screen correctly.  Not sure how the scaling works in your program but this will work as an a way to get it to look good.  Auto-scaling would of course be a nice feature.

Thanks again for your quick response on this.

**Comment by heatvent** [comment]
Jeff, sorry for all the posts but not sure whey but the issue comes up again in different environments ... not sure what is going on but I have had times where it looks like the racing screen scales correctly and others where the font seems to be the max 85px and I can only see through say lane 5.  I'm pretty sure I can just compensate by changing the max to 32px but I tried your latest release and everything went back to the larger font size.  I will see if I can reliably get a good screen using 32px.  Otherwise, I think there may be something going on with how the scaling works.

**Comment by jeffpiazza** [comment]
This should have been fixed by 2d25df8a155f5164639a9b1fc6ee83f8161f5554.  I'll reopen if you're still seeing a problem.
