### ISSUE TITLE
Confusing results in race history with "number lanes in reverse" checked. 

### ISSUE THREAD

**Issue by doughecka** [jeffpiazza/derbynet#333]
Just ran a race today, and after talking to someone afterwards about why they didn't win 1st place in their group despite winning all 4 heats (running timed races), I started looking at the data and comparing the logs... We did enable 'number lanes in reverse' so that the crowd would see lane 1 on the left, lane 4 on the right. 

In the race history, I see one of the heat results indicated as such:
Heat finished: lane1: 3.047s lane2: 2.955s lane3: 2.980s lane4: 3.017s

however the exported data shows:
lane1: 3.017 lane2: 2.98 lane3: 2.955 lane4: 3.047
exported data shows that the car in lane 3 placed first, which matches the finish time and if I can recall correctly, the actual real world results. 

Is the race history showing the raw results from the gate before reversing the lanes? The now racing screen results seemed to match the results during the race, so it wasn't obvious there was a problem, if there even is one at all, but still confusing. 

I think the ultimate reason the car that won all its heats didn't even place should be because the winning cars were faster on average, if the slowest heat is ignored, but still analyzing the data to confirm that. 

Counting ALL results and using the point-based system instead of finish times results in this car placing 1st in this group.

**Comment by jeffpiazza** [comment]
Nothing worse than a disputed result and a family that believes they were cheated!

The "reverse lane numbering" setting is intended to overcome a discrepancy between the numbering the timer uses, and the numbering everyone else (including the race crew) uses.  This is a relatively rare circumstance, something that happens if e.g. the track timer got replaced, or someone painted numbers on the lanes that were reversed from the timer.

The "reverse lane numbering" setting is not something that gets conveyed to the timer.  The race history shows the results as reported by the timer, which will be reversed from the lane numbers seen most everywhere else in this case.  That's understandably confusing; the race history page is something of a work in progress.  It's not otherwise an indication of a problem.  (Thankfully!)

You could spot-check the recorded results against remembered finish place, where you have them.  In particular, you might want to confirm that the "won all the heats" car is shown winning all their heats.  You probably already did this.

Point-based racing and timed racing are very likely to yield different standings for a round.  This is, as you suggest, because a first-place finish against three slow cars looks the same, for points, as a first-place finish against the very fastest cars in the field.  Identifying the fastest car(s) with point-based racing usually requires a lot of elimination rounds.

Were there more than one car that won all their heats?  That's common, and might help your disappointed racer understand the fairness of the result.

**Comment by chunter2** [comment]
If it's any help I used this feature when our timer was installed backwards on the track.  Saved us having to re-install it.

**Comment by doughecka** [comment]
Thanks for the response, I think it's all figured out now, once I threw the results into Excel Pivot table and confirmed the average numbers for the cars, heats, and lanes. We did have to re-run the first heat because a car was mixed up, and the second run was actually slower for all 4 cars... I suppose we could have re-run just that one car and manually entered the result into that heat. Naturally they think that the point-based racing would better (don't trust the timer), but as you said, that usually results in running more rounds to solve all the ties. Is Derbynet able to do PerfectN or something like that when operating in points mode? I feel like with timers PN isn't really needed... timers eliminate the need to deal with points in the first place.
