### ISSUE TITLE
Feature Request - Help Documents From Web GUI

### ISSUE THREAD

**Issue by heatvent** [jeffpiazza/derbynet#45]
It would be great to be able to access the docs either by serving up the pdf or embedding in web pages directly from the GUI rather than finding them on a drive.  If you are accessing DerbyNet remotely, you have to log into the remote computer to find the docs.  Not a big issue but more of an inconvenience that can be easily addressed I would think.

**Comment by jrowen** [comment]
A lot of the help docs appear to be viewable online at http://jeffpiazza.github.io/derbynet (see menu button), but aren't visible from a mobile device held in portrait mode.  If I turn the device to landscape, the menu bar with the link to the docs appears.  Adding a hamburger or similar menu functionality for mobile devices would be useful.

**Comment by ScouterAndy** [comment]
Further to this... we often run our events with a "private" WiFi network that all the devices in use connect into; since most devices can't also connect to a real "public" WiFi at the same time, that means they can't access anything online.  So having an easy way to get at the docs as part of the web server tree would be a great feature.   Then everybody who had access to the software would have access to the docs at the same time.

**Comment by jeffpiazza** [comment]
e0df8e92707f9a123970c79923abd16ab57b4627 includes a "quick ref" document accessible from the banner bar on each page.  I realize that's not the same as providing the full set of documentation pdfs on the server; my premise is that users onsite need access to a short reference sheet rather than the more long-winded material.

Feedback welcome on whether this answers the needs as you experience them, and what's missing if not.

jrowen, I think your comment is mostly a different issue; though it's not an unreasonable goal, I'm not sure how feasible it is to convert the GitHub.io pages to be fully mobile-friendly.
