### ISSUE TITLE
Using sprintf for average time in standings causes confusion for possible tie

### ISSUE THREAD

**Issue by jeepin95** [jeffpiazza/derbynet#74]
On the standings display it appears that using sprintf for the avg time display is causing a "rounding" error. We had 2nd and 3rd places racers show as both having an average of 2.079 but not tied when displaying only 4 digits. While one way to clear this up in our case would have been to display 5 digits, it would not have been an issue at 4 if the display would have rounded rather than using sprintf.

Racer 1 had a 5 digit average of 2.0787 actually 2.07866666 (which was correctly displayed in 4 digits as 2.079) The system did correctly put Racer 2 in 2nd place.
Racer 2 had a 5 digit average of 2.0795 (which was incorrectly displayed in 4 digits as 2.079 instead of 2.080) The system did correctly put Racer 3 in 3rd place.

The issue was more a visibility thing that caused some questions and brief concerns from the audience as to why Racer 1 and Racer 2 were not counted as a tie for purposes of moving into the finals. As we were setup, Racer 2 did not advance as their standings were not high enough to advance.

**Comment by jeffpiazza** [comment]
Any chance the 2.0795 was really something like 2.07949?  That would round to 2.0795 or 2.079.

**Comment by jeepin95** [comment]
> Any chance the 2.0795 was really something like 2.07949? That would round to 2.0795 or 2.079.

I believe it has to do with how 2.0795 would be stored as a double and then treated by the sprintf function. I believe it gets stored as 2.0794999999... and sprintf doesn't behave as it should when rounding.

The time values we had were:
2.105
2.069
2.102
2.083
2.069
2.049
= 12.477 / 6 = 2.0795

I'm sure there are much better ways to do this, but just for a test I forked and did a very quick check at https://github.com/jeepin95/derbynet/commit/dcb184778f5001bb17f815ed9667c4d76d6f903d by passing the rounded value, which did result in rounding the time in question to 2.080.

I also manually tried the code below, notice how the first result does not round correctly.
```php
php > $a = 2.0795;
php > echo sprintf('%5.3f',$a);
2.079
php > echo round($a,3);
2.08
php > echo sprintf('%5.3f',round($a,3));
2.080
php >
```   

Also, this was our first time with it, but we loved DerbyNet.

**Comment by heatvent** [comment]
HI, I was just following the thread ... is it 2.079 because you are working with 3 decimal places as the inputs.  Seems odd to me to take the average to 4 decimal places if the inputs are at 3 decimal places. Also, if I just use a 10-key calculator set to 3 decimals and divide 12.477 by 6 I get 2.079 because it cuts off the 4th decimal point (displays just the first 3) rather than rounding up or down.  My guess is the race scores from the timer are delivered to DerbyNet in thousandths so that is the level of accuracy for determining who won the race.  I guess it could makes sense to display 4 decimal places so people can see why (basically racer one had the lowest cumulative time).  Not sure I would display race results to the audience but this could help explain if somewhat asks what their time was versus the competition.

**Comment by jeepin95** [comment]
The system does support ties, which I verified by manually entering 1,2,3,4,5,6 as the times through a set of heats resulting in ties. Our timer precision was 3 decimal places. In my opinion using additional precision when calculating the average is appropriate, and resulted in the appropriate ranking of the racers. The only issue was with the displaying of the average times. I think that the way the software computed rankings was both mathematically accurate, and logical. This would be my preference for how to handle the rankings. Using round() to the desired places and inputting that result into sprintf produced what I believe is the correct view in this case. What I need to dig further into is at what point it calculates the rank in order to make sure the rounding is done there also. What it should probably do is properly round the averages to 4 decimals since that is the max option to display, then calculate the placement to account for ties at 4 decimals. Another option would be full float precision for the averaging and ranking, with an * if a rounded display makes it *look* like it should have been a tie, but in reality wasn't.

On the other hand, I could understand if it just chopped off the additional precision without rounding, as long as that was how it actually computed results to include ties. If it calculated the rankings using what it displays as the average times, then those two racers would have ranked the same in a tie for first place.

There are at least a few SO entries on sprintf and the unexpected "rounding" results it offers.
https://stackoverflow.com/questions/27107238/why-does-phps-sprintf-not-round-5s-reliably

I did like the capability to display race results to the audience, and the ability to export the results to CSV and share later, allowing the data nerds to do some analysis.

**Comment by heatvent** [comment]
Maybe one solution would be to display the cumulative time in addition to the average.  The cumulative could be kept at 3 decimal points and it would be clear who the winner is.

**Comment by jeepin95** [comment]
> Maybe one solution would be to display the cumulative time in addition to the average. The cumulative could be kept at 3 decimal points and it would be clear who the winner is.

That would certainly have worked in this situation, and would work to 3 or 4 decimal places depending on the settings selected.

**Comment by jeffpiazza** [comment]
I probably shouldn't have left this open for so long.

All the calculations for averages and standings are done in the native floating-point representation.  That is, there's no artificial limit on digits used in the calculations themselves, including the determination of standings and ties.  You're mostly describing concerns about how the numbers are presented rather than how they're calculated.

From a narrow "correctness" perspective, there are several different rounding rules that might be used [1]; the rules we all learned in grade school don't necessarily apply.  Rounding for floating-point numbers is trickier than you might think, and for the most part I'm not inclined to second-guess the PHP implementation.  I assume that sprintf is just applying one of these alternative rounding rules.

I think that with that understanding, an apparent tie like you experienced should be explainable to your audience (and would be rare in any event).

[1] Have a look at the 'mode' argument in https://www.php.net/manual/en/function.round.php
